version: "3.8"

services:
  firemap:
    build: .
    environment:
      - PORT=7291
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    volumes:
      - cache:/app/cache

volumes:
  cache:
